### ISSUE TITLE
  raise Exception("RNN : Input dimension should be rank 3 : [batch_size, n_steps, n_features]") Exception: RNN : Input dimension should be rank 3 : [batch_size, n_steps, n_features]

### ISSUE THREAD

**Issue by monajalal** [GuangmingZhu/Conv3D_BICLSTM#2]
How should I fix this?
```

mona@Mona:~/code/gesture/Conv3D_BICLSTM$ python training_isogr_depth.py 
/home/mona/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-22 11:29:38.108920: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[TL] WARNING: From /home/mona/code/gesture/Conv3D_BICLSTM/c3d_biclstm.py:13: set_name_reuse (from tensorlayer.layers.utils) is deprecated and will be removed after 2018-06-30.
Instructions for updating: TensorLayer relies on TensorFlow to check name reusing

[TL] WARNING: this method is DEPRECATED and has no effect, please remove it from your code.
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
Traceback (most recent call last):
  File "training_isogr_depth.py", line 50, in <module>
    _,networks = net.c3d_biclstm(x, num_classes, False, True)
  File "/home/mona/code/gesture/Conv3D_BICLSTM/c3d_biclstm.py", line 79, in c3d_biclstm
    name='fwclstm_layer_1')
  File "/home/mona/anaconda2/lib/python2.7/site-packages/tensorlayer/decorators/deprecated_alias.py", line 24, in wrapper
    return f(*args, **kwargs)
  File "/home/mona/anaconda2/lib/python2.7/site-packages/tensorlayer/layers/recurrent.py", line 184, in __init__
    raise Exception("RNN : Input dimension should be rank 3 : [batch_size, n_steps, n_features]")
Exception: RNN : Input dimension should be rank 3 : [batch_size, n_steps, n_features]

```

**Comment by aserchen** [comment]
@monajalal  I meet the same problem, both WARNING and Traceback info! Have you solved this?

**Comment by GuangmingZhu** [comment]
The original Tensorlayer does not support the convolutional LSTM, so the tensorlayer/layers.py needs to be replaced with our tensorlayer-layers.py. Just follow the README exactly, I believe it will be OK.
